const versiRumi = [
    // hamzah berumah - ئ
    "ateisme",
    "diet",
    "frekuensi",
    "malaikat",
    "masalah",
    "monoteisme",
    "tahniah",
    // zoh - ظ
    "zalim",
    "kezaliman",
    "hafaz",
    "berlafaz",
    // va - ۏ
    "larva",
    "novel-novel",
    "videografi",
    "november",
    "pemvaksinan",
    "biodiversiti",
    // tsa - ث
    "isnin",         "rabu","khamis","jumaat","sabtu","ahad",
    "selasa",
    "misalnya",
    "dibahaskan",
    // kho - خ
    "akhir",
    "khabar",
    "khat",
    "dikhianati",
    "mengkhuatiri",
    // dzal - ذ
    "lazat",
    "berbeza",
    "izin",
    "pengizinan",
    "ustazah",
    // zai - ز
    "etnomuzikologi",
    "trapezium",
    "zirafah",
    "berzina",
    // sod - ص
    "sahabatnya",
    "nasihat",
    "muslihat",
    "maksud",
    "solat",
    "kesihatan",
    // dod - ض
    "darurat",
    "ramadan",
    "hadir",
    // ein - ع
    "ilmu",
    "umumnya",
    "berumur",
    "saat",
    "manfaat",
    "maklumat",
    // ghain - غ
    "loghat",           // FIX USELESS ZWNJ
    "istighfar",
    "ghaib",
    "akibat",
    // dash - sempang
    "berhati-hati",
    "rupa-rupanya",
    // ZWNJ
    "konteks",
    "teks",         // indeks اينديک‌س- salah? MANY MORE
    "interseks",
    "sains",
    "ambulans",
    "insurans",



    "muncul",
    "bahasa",
    "internet",
    "komputer",
    "terjemah",
    "perisian",
    "bermain",
    "perempuan",
    "lelaki",
    "jumlah",
    "memiliki",
    "keseluruhan",
    "pendidikan",
    "kebangsaan",
    "mampu",
    "sumber",
    "penduduk",
    "duduk",
    "bilangan",
    "nombor",
    "kira",
    "menurut",
    "awak",
    "kita",
    "seseorang",
    "serangga",
    "spesies",
    "pelbagai",
    "langsung",
    "labah-labah",
    "kebenaran",
    "kepala",
    "lumpur",
    "belalang",
    "kupu-kupu",
    "lalat",
    "karbon",
    "musim",
    "jarak",
    "iklim",
    "manusia",
    "jika",
    "matahari",
    "olahraga",
    "tanggungjawab",
    "kakitangan",
    "terima",
    "makhluk",
    "keadaan",
    "kosmetik",
    "kegelapan",
    "penampilan",
    "keindahan",
    "niaga",
    "ekonomi",
    "pisang",
    "sayuran",
    "bawang",
    "minyak",
    "penjajahan",
    "hapus",
    "pembasmian",
    "genosid",
    "rasisme",
    "istimewa",
    "nusantara",
    "e-mel",        // إي-ميل PERLU DIPERBAIKI
    "baik",
    "lawa",
    "filipina",     // فيليڤينا PERLU TAMBAH
    "republik",
    "anjing",
    "lautan",
    "kongsi",
    "cukup",
    "cawan",
    "pisau",
    "kuih",
    "longkang",
    "maaf",
    "lobak",
    "perdana",
    "raksasa",
    "wanita",
    "langgan",
    "pepijat",
    "alam",
    "skrol",
    "glasier",
    "alhamdulillah",
    "ringgit",
    "rupiah",
    "layan",
    "ayah",
    "asyik",
    "tanya",
    "semoga",
    "roti",
    "upacara",
    "waktu",
    "sahaja",
    "syarat",
    "buku-buku",




    // top 130 common wikipedia words
    "dan",
    "yang",
    //"di",
    "pada",
    "dalam",
    "dengan",
    "untuk",
    "ini",
    "tahun",
    //"ke",
    "oleh",
    "dari",
    "sebagai",
    "telah",
    "tidak",
    "juga",
    "adalah",
    "kepada",
    "merupakan",
    "itu",
    "malaysia",
    "daripada",
    "atau",
    "bahasa",
    "mereka",
    "beliau",
    "satu",
    "orang",
    "menjadi",
    "bagi",
    "negara",
    "lebih",
    "ia",
    "ialah",
    "lain",
    "seperti",
    "sebuah",
    "mempunyai",
    "negeri",
    "akan",
    "boleh",
    "kawasan",
    "pertama",
    "nama",
    "dunia",
    "masjid",
    "hari",
    "amerika",
    "antara",
    "secara",
    "bahawa",
    "besar",
    "syarikat",
    "kerana",
    "kerajaan",
    "tersebut",
    "tetapi",
    "kumpulan",
    "tentera",
    "iaitu",
    "seorang",
    "melayu",
    "selepas",
    "luar",
    "dua",
    "perang",
    "ya",
    "digunakan",
    "serta",
    "beberapa",
    "sultan",
    "terdapat",
    "islam",
    "raja",
    "bandar",
    "banyak", "kebanyakan",
    "raya",
    "utama", "terutamanya",
    "baru",
    "sekolah",
    "indonesia",
    "masa",
    "menteri",
    "ketika",
    "daerah",
    "pulau",
    "ahli",
    "atas",
    "tanah",
    "air",
    "kampung",
    "menggunakan",
    "sungai",
    "sistem",
    "tempat",
    "apabila",
    "web",
    "bawah",
    "kuala",
    "lagi",
    "selatan", "utara", "barat", "timur", "tenggara",
    "hanya",
    "dapat",
    "dikenali",
    "sama",
    "sehingga",
    "kebangsaan",
    "melalui",
    "anak",
    "lihat",
    "ada", "mengadakan",
    "sebelum",
    "termasuk",
    "dia",
    "terbang",
    "sejarah",
    "kemudian",
    "hingga",
    "bahagian",
    "laut",
    "kini",
    "kapal",
    "filem",
    "terletak",
    "salah",
    "parti",
    "bermula",
    "kota",
    "pilihan",
    "terhadap", "terhadap",
];




const wordBank = [
  "اتيئيسمى",
    "ديئت",
    "فريکوئنسي",
    "ملائکة",
    "مسئله",
    "مونوتيئيسمى",
    "تهنيئه",
    // zoh - ظ
    "ظاليم",
    "کظاليمن",
    "حفظ",
    "برلفظ",
    // ۏا - ۏ
    "لرۏا",
    "نوۏل٢",
    "ۏيديوݢرافي",
    "نوۏيمبر",
    "ڤمۏکسينن",
    "بيوديۏرسيتي",
    // tsa - ث
    "اثنين",         "رابو","خميس","جمعة","سبت","اهد",
    "ثلاث",
    "ميثلڽ",
    "دبحثکن",
    // kho - خ
    "اخير",
    "خبر",
    "خط",
    "دخيانتي",
    "مڠخواطيري",
    // dzal - ذ
    "لاذت",
    "بربيذا",
    "ايذين",
    "ڤڠيذينن",
    "استاذه",
    // زاي - ز
    "ايتنوموزيکولوݢي",
    "تراڤيزيوم",
    "زرافه",
    "برزنا",
    // صاد - ص
    "صحابتڽ",
    "نصيحت",
    "مصليحت",
    "مقصود",
    "صلاة",
    "کصيحتن",
    // dod - ض
    "ضرورة",
    "رمضان",
    "حاضير",
    // ein - ع
    "علمو",
    "عمومڽ",
    "برعمور",
    "ساعت",
    "منفعت",
    "معلومت",
    // غين - غ
    "لوغت",           // FIX USELESS ZWNJ
    "استغفار",
    "غاءيب",
    "عاقبة",
    // dash - سمڤڠ
    "برهاتي-هاتي",
    "روڤا-روڤاڽ",
    // ZWNJ
    "کونتيک‌س",
    "تيک‌س",         // اينديک‌س اينديک‌س- ساله؟ MANY MORE
    "اينترسيک‌س",
    "ساءين‌س",
    "امبولن‌س",
    "اينسورن‌س",



    "مونچول",
    "بهاس",
    "اينترنيت",
    "کومڤوتر",
    "ترجمه",
    "ڤرايسين",
    "برماءين",
    "ڤرمڤوان",
    "للاکي",
    "جومله",
    "مميليقي",
    "کسلوروهن",
    "ڤنديديقن",
    "کبڠساءن",
    "ممڤو",
    "سومبر",
    "ڤندودوق",
    "دودوق",
    "بيلڠن",
    "نومبور",
    "کيرا",
    "منوروت",
    "اوق",
    "کيت",
    "سسأورڠ",
    "سرڠݢ",
    "سڤيسيس",
    "ڤلباݢاي",
    "لڠسوڠ",
    "لابه٢",
    "کبنرن",
    "کڤالا",
    "لومڤور",
    "بلالڠ",
    "کوڤو٢",
    "لالت",
    "کربون",
    "موسيم",
    "جارق",
    "اقليم",
    "ماءنسي",
    "جک",
    "ماتاهاري",
    "اولهراݢ",
    "تڠݢوڠجواب",
    "کاکيتاڠن",
    "تريما",
    "مخلوق",
    "کأداءن",
    "کوسميتيک",
    "کݢلڤن",
    "ڤنمڤيلن",
    "کأيندهن",
    "نياݢ",
    "ايکونومي",
    "ڤيسڠ",
    "سايورن",
    "باوڠ",
    "ميڽق",
    "ڤنجاجهن",
    "هاڤوس",
    "ڤمبسمين",
    "ݢينوسيد",
    "راسيسمى",
    "ايستيميوا",
    "نوسنتارا",
    "إي-ميل",
    "باءيق",
    "لاوا",
    "فيليڤينا",     // فيليڤينا ڤرلو تمبه
    "ريڤوبليک",
    "انجيڠ",
    "لاءوتن",
    "کوڠسي",
    "چوکوڤ",
    "چاون",
    "ڤيساو",
    "کوءيه",
    "لوڠکڠ",
    "معاف",
    "لوبق",
    "ڤردان",
    "رقساس",
    "وانيتا",
    "لڠݢن",
    "ڤڤيجت",
    "عالم",
    "سکرول",
    "ݢلاسيئر",
    "الحمدالله",
    "ريڠݢيت",
    "روڤياه",
    "لاين",
    "ايه",
    "عاشيق",
    "تاڽ",
    "سموݢ",
    "روتي",
    "اوڤاچارا",
    "وقتو",
    "سهاج",
    "شرط",
    "بوکو٢",




    // توڤ 130 common wikipedia words
    "دان",
    "يڠ",
    //"د",
    "ڤد",
    "دالم",
    "دڠن",
    "اونتوق",
    "اين",
    "تاهون",
    //"ک",
    "اوليه",
    "دري",
    "سباݢاي",
    "تله",
    "تيدق",
    "جوݢ",
    "اداله",
    "کڤد",
    "مروڤاکن",
    "ايت",
    "مليسيا",
    "درڤد",
    "اتاو",
    "بهاس",
    "مريک",
    "بلياو",
    "ساتو",
    "اورڠ",
    "منجادي",
    "باݢي",
    "نݢارا",
    "لبيه",
    "اي",
    "اياله",
    "لاءين",
    "سڤرتي",
    "سبواه",
    "ممڤوڽاءي",
    "نݢري",
    "اکن",
    "بوليه",
    "کاوسن",
    "ڤرتام",
    "نام",
    "دنيا",
    "مسجد",
    "هاري",
    "اميريکا",
    "انتارا",
    "سچارا",
    "بهاوا",
    "بسر",
    "شريکت",
    "کران",
    "کراجاءن",
    "ترسبوت",
    "تتاڤي",
    "کومڤولن",
    "تنترا",
    "ياءيت",
    "سأورڠ",
    "ملايو",
    "سلڤس",
    "لوار",
    "دوا",
    "ڤرڠ",
    "ياء",
    "دݢوناکن",
    "سرتا",
    "ببراڤ",
    "سلطان",
    "ترداڤت",
    "إسلام",
    "راج",
    "باندر",
    "باڽق", "کباڽقن",
    "راي",
    "اوتام", "تراوتاماڽ",
    "بارو",
    "سکوله",
    "ايندونيسيا",
    "ماس",
    "منتري",
    "کتيک",
    "داءيره",
    "ڤولاو",
    "اهلي",
    "اتس",
    "تانه",
    "اءير",
    "کامڤوڠ",
    "مڠݢوناکن",
    "سوڠاي",
    "سيستم",
    "تمڤت",
    "اڤابيلا",
    "ويب",
    "باوه",
    "کوالا",
    "لاݢي",
    "سلاتن", "اوتارا", "بارت", "تيمور", "تڠݢارا",
    "هاڽ",
    "داڤت",
    "دکنلي",
    "سام",
    "سهيڠݢ",
    "کبڠساءن",
    "ملالوءي",
    "انق",
    "ليهت",
    "اد", "مڠاداکن",
    "سبلوم",
    "ترماسوق",
    "دي",
    "تربڠ",
    "سجاره",
    "کمودين",
    "هيڠݢ",
    "بهاݢين",
    "لاءوت",
    "کيني",
    "کاڤل",
    "فيلم",
    "ترلتق",
    "ساله",
    "ڤرتي",
    "برمولا",
    "کوتا",
    "ڤيليهن",
    "ترهادڤ", "ترهادڤ",
];
